In [1]:
import os
import pandas as pd

def find_csv_files(directory):
    # List to hold the rows of the new DataFrame
    data = []
    
    # Walk through the directory
    for root, _, files in os.walk(directory):
        for file in files:
            # Check if the file is a .qasm file
            if file.endswith('.csv') and 'solutions' in file:
                # Construct the full path to the .qasm file
                solutions_csv = os.path.join(root, file)
                origin_qc = root.split('mutants_')[-1]
                
                gates_csv = solutions_csv.replace(f'best_solutions', f'suspicious_gates')
                
                if 'Add' in file or 'Remove' in file or 'Replace' in file:
                    splited = file.split('_')
                    mutation_pos = int(splited[8].replace('P',''))
                    mutant_operator = splited[6]
                    qubits = int(splited[4])
                else:
                    splited = file.split('_')
                    mutation_pos = int(splited[-1].replace('P','').replace('.csv',''))
                    mutant_operator = splited[6]
                    qubits = int(splited[5])
                    
                if qubits == 2:
                    total_positions = 18
                elif qubits == 3:
                    total_positions = 18
                elif qubits == 4:
                    total_positions = 49
                elif qubits == 5:
                    total_positions = 55
                elif qubits == 6:
                    total_positions = 37
                elif qubits == 7:
                    total_positions = 41
                elif qubits == 8:
                    total_positions = 55
                elif qubits == 9:
                    total_positions = 59
                elif qubits == 10:
                    total_positions = 48
                elif qubits == 11:
                    total_positions = 43
                elif qubits == 12:
                    total_positions = 37
                elif qubits == 13:
                    total_positions = 27
                    
                #print(solutions_csv)
                # Check if the corresponding .csv file exists
                if os.path.exists(solutions_csv) and os.path.exists(gates_csv):
                    # Read the first row of the CSV file
                    first_row_solutions = pd.read_csv(solutions_csv, nrows=1)
                    gates_df = pd.read_csv(gates_csv)
                    if mutation_pos in gates_df['Position'].values:
                        sus_pos = (gates_df[gates_df['Position']==mutation_pos].index[0] / total_positions) * 100
                    else:
                        sus_pos = 100
                    row_data = {'origin_qc': origin_qc, 'filename': file,'mutation_pos': mutation_pos, 'mutation_operation':mutant_operator, 'Score': first_row_solutions['Score'].iloc[0], 'Fix_operation': first_row_solutions['Operator'].iloc[0], 'Fixed_gate':first_row_solutions['Gate'].iloc[0], 'New_gate':first_row_solutions['New_gate'].iloc[0], 'Fix_pos':first_row_solutions['Position'].iloc[0], 'Mutation_sus_pos': sus_pos, 'Exec_time':  first_row_solutions['Total_exec_time'].iloc[0], 'Overall_improvement_percent':first_row_solutions['Overall_improvement_percent'].iloc[0]}
                    data.append(row_data)
    
    # Create a new DataFrame from the collected data
    df = pd.DataFrame(data)
    
    # Manually add the results obtained from the Bugs4Q benchmark
    df.loc[len(df)] = ["bugs4q-id25", "best_solutions_for_Bug4Q_id25.csv", 3, "SQ", 7.637732, "Replace", "ccx", "r", 2, 50, 431.749625, 3.589870]
    df.loc[len(df)] = ["bugs4q-id26", "best_solutions_for_Bug4Q_id26.csv", 2, "Replace", 0, "Replace", "h", "rx", 1, 0, 17.291166, 100]
    df.loc[len(df)] = ["bugs4q-id27", "best_solutions_for_Bug4Q_id27.csv", 8, "Reverse", 0, "Add", "t", "swap", 7, 76.470588, 82.627925, 100]
    df.loc[len(df)] = ["bugs4q-id39", "best_solutions_for_Bug4Q_id39.csv", 0, "Delete", 23.646314, "Add", "cx", "h", 0, 90, 2437.438162, 10.620157]
    
    df.to_csv('results_summary.csv')
    
    return df

,Unnamed: 0,origin_qc,filename,mutation_pos,mutation_operation,Score,Fix_operation,Fixed_gate,New_gate,Fix_pos,Mutation_sus_pos,Exec_time,Overall_improvement_percent
0,0,ae_3,best_solutions_for_ae_3_Mutant_Remove_h_P10_Q1...,10,Remove,0.000000,Add,cp,h,10,0.000000,211.277337,100.000000
1,1,ae_3,best_solutions_for_ae_3_Mutant_Replace_t_P10_Q...,10,Replace,0.000000,Replace,t,h,10,0.000000,136.264315,100.000000
2,2,ae_3,best_solutions_for_Mutant_ae_3_QGI_45_P7.csv,7,QGI,0.000000,Delete,u,NaN,2,11.111111,6.393282,100.000000
3,3,dj_11,best_solutions_for_dj_11_Mutant_Remove_u_P30_Q...,30,Remove,0.000000,Add,NaN,h,37,4.651163,5793.069563,100.000000
4,4,dj_11,best_solutions_for_Mutant_dj_11_QGI_58_P8.csv,8,QGI,0.000000,Delete,y,NaN,8,0.000000,6.579843,100.000000
5,5,dj_11,best_solutions_for_Mutant_dj_11_QGR_404_P29.csv,29,QGR,1.000000,Delete,cx,NaN,11,37.209302,7208.986360,0.000000
6,6,ghz_13,best_solutions_for_ghz_13_Mutant_Add_rx_P5_Q8_...,5,Add,0.000000,Delete,rx,NaN,5,0.000000,6.197106,100.000000
7,7,ghz_13,best_solutions_for_ghz_13_Mutant_Remove_cx_P8_...,8,Remove,3.927652,Replace,h,rzx,0,88.888889,7221.382287,47.835243
8,8,ghz_13,best_solutions_for_ghz_13_Mutant_Replace_cp_P1...,1,Replace,3.930124,Replace,h,cy,0,37.037037,7213.587165,32.637793
9,9,graphstate_12,best_solutions_for_graphstate_12_Mutant_Remove...,22,Remove,3.883773,Replace,cz,ryy,22,0.000000,7208.831975,24.793475
10,10,graphstate_12,best_solutions_for_graphstate_12_Mutant_Replac...,23,Replace,4.130000,Add,cx,r,23,59.459459,7209.886941,6.911632
11,11,graphstate_12,best_solutions_for_Mutant_graphstate_12_QGI_73...,5,QGI,0.000000,Delete,y,NaN,5,0.000000,6.618479,100.000000
12,12,grover_4,best_solutions_for_grover_4_Mutant_Remove_p_P1...,19,Remove,0.000000,Add,cx,z,7,42.857143,50.817927,100.000000
13,13,grover_4,best_solutions_for_Mutant_grover_4_QGI_367_P32...,32,QGI,0.000000,Delete,ry,NaN,32,0.000000,6.817854,100.000000
14,14,grover_4,best_solutions_for_Mutant_grover_4_QGR_833_P39...,39,QGR,0.000000,Add,cx,rxx,36,83.673469,164.207464,100.000000
15,15,qaoa_6,best_solutions_for_qaoa_6_Mutant_Add_swap_P9_Q...,9,Add,0.000000,Delete,swap,NaN,9,0.000000,6.209644,100.000000
16,16,qaoa_6,best_solutions_for_qaoa_6_Mutant_Remove_rx_P12...,12,Remove,0.022162,Add,h,r,12,78.378378,4919.507306,99.415539
17,17,qaoa_6,best_solutions_for_qaoa_6_Mutant_Replace_t_P20...,20,Replace,0.031250,Replace,t,rx,20,2.702703,5163.893562,99.247887
18,18,qft_9,best_solutions_for_Mutant_qft_9_QGR_708_P12.csv,12,QGR,0.638838,Replace,r,rz,12,0.000000,7211.683209,83.613401
19,19,qft_9,best_solutions_for_qft_9_Mutant_Add_swap_P11_Q...,11,Add,0.000000,Delete,swap,NaN,11,0.000000,6.542583,100.000000
20,20,qft_9,best_solutions_for_qft_9_Mutant_Remove_cp_P23_...,23,Remove,0.000000,Add,cp,crz,11,32.203390,6313.353427,100.000000
21,21,qnn_2,best_solutions_for_Mutant_qnn_2_QGR_208_P7.csv,7,QGR,0.000000,Replace,iswap,cx,7,5.555556,18.221934,100.000000
22,22,qnn_2,best_solutions_for_qnn_2_Mutant_Add_rx_P9_Q0_[...,9,Add,0.000000,Delete,rx,NaN,9,0.000000,6.467602,100.000000
23,23,qnn_2,best_solutions_for_qnn_2_Mutant_Remove_ry_P11_...,11,Remove,0.000000,Add,u,rx,0,72.222222,62.094230,100.000000
24,24,qpe_8,best_solutions_for_Mutant_qpe_8_QGI_296_P24.csv,24,QGI,0.000000,Delete,x,NaN,24,0.000000,6.816455,100.000000
25,25,qpe_8,best_solutions_for_Mutant_qpe_8_QGR_841_P30.csv,30,QGR,1.875716,Replace,rxx,p,30,58.181818,7210.961848,33.707266
26,26,qpe_8,best_solutions_for_qpe_8_Mutant_Remove_h_P6_Q6...,6,Remove,0.000000,Add,h,ry,0,94.545455,135.698701,100.000000
27,27,qwalk_5,best_solutions_for_Mutant_qwalk_5_QGI_339_P40.csv,40,QGI,0.000000,Delete,sdg,NaN,40,0.000000,7.406415,100.000000
28,28,qwalk_5,best_solutions_for_qwalk_5_Mutant_Remove_x_P13...,13,Remove,0.000000,Add,u,x,15,70.909091,212.054323,100.000000
29,29,qwalk_5,best_solutions_for_qwalk_5_Mutant_Replace_t_P5...,5,Replace,0.000000,Add,rccx,r,9,20.000000,431.694072,100.000000
30,30,vqe_7,best_solutions_for_Mutant_vqe_7_QGI_347_P25.csv,25,QGI,0.000000,Delete,rx,NaN,25,0.000000,6.366112,100.000000
31,31,vqe_7,best_solutions_for_Mutant_vqe_7_QGR_752_P24.csv,24,QGR,0.000000,Replace,rx,cx,24,0.000000,2574.960093,100.000000
32,32,vqe_7,best_solutions_for_vqe_7_Mutant_Remove_ry_P2_Q...,2,Remove,0.000000,Replace,ry,ry,0,41.463415,2810.067075,100.000000
33,33,wstate_10,best_solutions_for_wstate_10_Mutant_Add_rxx_P2...,20,Add,0.000000,Delete,rxx,NaN,20,0.000000,6.611835,100.000000
34,34,wstate_10,best_solutions_for_wstate_10_Mutant_Remove_ry_...,1,Remove,0.000000,Add,ry,ry,1,0.000000,848.990076,100.000000
35,35,wstate_10,best_solutions_for_wstate_10_Mutant_Replace_rz...,14,Replace,2.118129,Add,rzz,rz,14,25.000000,7209.583341,52.775510
36,36,bugs4q-id25,best_solutions_for_Bug4Q_id25.csv,3,SQ,7.637732,Replace,ccx,r,2,50.000000,431.749625,3.589870
37,37,bugs4q-id26,best_solutions_for_Bug4Q_id26.csv,2,Replace,0.000000,Replace,h,rx,1,0.000000,17.291166,100.000000
38,38,bugs4q-id27,best_solutions_for_Bug4Q_id27.csv,8,Reverse,0.000000,Add,t,swap,7,76.470588,82.627925,100.000000
39,39,bugs4q-id39,best_solutions_for_Bug4Q_id39.csv,0,Delete,23.646314,Add,cx,h,0,90.000000,2437.438162,10.620157

In [ ]:
# directory = r'FINAL_results_it5_run0'
# result_df = find_csv_files(directory)

result_df = pd.read_csv('FINAL_results_it5_run0/results_summary.csv')
result_df

In [4]:
# Calculate the percentage of rows with a Score of 0
score_zero_percentage = (result_df['Score'] == 0).mean() * 100

# Calculate the percentage of each operator in the rows with a Score of 0
df_score_zero = result_df[result_df['Score'] == 0]
mutant_operator_percentages = df_score_zero['mutation_operation'].value_counts(normalize=True) * 100
fix_operator_percentages = df_score_zero['Fix_operation'].value_counts(normalize=True) * 100
avg_fix_time = df_score_zero['Exec_time'].mean()

df_not_fixed = result_df[result_df['Score'] > 0]
avg_improvement = df_not_fixed['Overall_improvement_percent'].mean()

top_gates_avg = df_not_fixed['Mutation_sus_pos'].mean()

# Display the results
print(f'Percentage of fixed mutants: {score_zero_percentage}% in a avg of {avg_fix_time}s\n')
print(f'The mutants that were not fixed, obtained an avg of {avg_improvement}% improvement.\n')

print(f'In the not fixed mutants ({100-score_zero_percentage}%), the suspicious gate was in avg in the top {round(top_gates_avg)}% of most suspicious gates.\n')

df_not_fixed

Percentage of fixed mutants: 70.0% in a avg of 712.2041727479667s

The mutants that were not fixed, obtained an avg of 41.26231449225709% improvement.

In the not fixed mutants (30.0%), the suspicious gate was in avg in the top 90% of most suspicious gates.

,Unnamed: 0,origin_qc,filename,mutation_pos,mutation_operation,Score,Fix_operation,Fixed_gate,New_gate,Fix_pos,Mutation_sus_pos,Exec_time,Overall_improvement_percent
5,5,dj_11,best_solutions_for_Mutant_dj_11_QGR_404_P29.csv,29,QGR,1.000000,Delete,cx,NaN,11,37.209302,7208.986360,0.000000
7,7,ghz_13,best_solutions_for_ghz_13_Mutant_Remove_cx_P8_...,8,Remove,3.927652,Replace,h,rzx,0,88.888889,7221.382287,47.835243
8,8,ghz_13,best_solutions_for_ghz_13_Mutant_Replace_cp_P1...,1,Replace,3.930124,Replace,h,cy,0,37.037037,7213.587165,32.637793
9,9,graphstate_12,best_solutions_for_graphstate_12_Mutant_Remove...,22,Remove,3.883773,Replace,cz,ryy,22,0.000000,7208.831975,24.793475
10,10,graphstate_12,best_solutions_for_graphstate_12_Mutant_Replac...,23,Replace,4.130000,Add,cx,r,23,59.459459,7209.886941,6.911632
16,16,qaoa_6,best_solutions_for_qaoa_6_Mutant_Remove_rx_P12...,12,Remove,0.022162,Add,h,r,12,78.378378,4919.507306,99.415539
17,17,qaoa_6,best_solutions_for_qaoa_6_Mutant_Replace_t_P20...,20,Replace,0.031250,Replace,t,rx,20,2.702703,5163.893562,99.247887
18,18,qft_9,best_solutions_for_Mutant_qft_9_QGR_708_P12.csv,12,QGR,0.638838,Replace,r,rz,12,0.000000,7211.683209,83.613401
25,25,qpe_8,best_solutions_for_Mutant_qpe_8_QGR_841_P30.csv,30,QGR,1.875716,Replace,rxx,p,30,58.181818,7210.961848,33.707266
35,35,wstate_10,best_solutions_for_wstate_10_Mutant_Replace_rz...,14,Replace,2.118129,Add,rzz,rz,14,25.000000,7209.583341,52.775510
36,36,bugs4q-id25,best_solutions_for_Bug4Q_id25.csv,3,SQ,7.637732,Replace,ccx,r,2,50.000000,431.749625,3.589870
39,39,bugs4q-id39,best_solutions_for_Bug4Q_id39.csv,0,Delete,23.646314,Add,cx,h,0,90.000000,2437.438162,10.620157

In [10]:
df_score_zero

,origin_qc,filename,mutation_pos,mutation_operation,Score,Fix_operation,Fixed_gate,New_gate,Fix_pos,Mutation_sus_pos,Exec_time,Overall_improvement_percent
0,ae_3,best_solutions_for_ae_3_Mutant_Remove_h_P10_Q1...,10,Remove,0.0,Add,cp,h,10,0.000000,211.277337,100.0
1,ae_3,best_solutions_for_ae_3_Mutant_Replace_t_P10_Q...,10,Replace,0.0,Replace,t,h,10,0.000000,136.264315,100.0
2,ae_3,best_solutions_for_Mutant_ae_3_QGI_45_P7.csv,7,QGI,0.0,Delete,u,NaN,2,11.111111,6.393282,100.0
3,dj_11,best_solutions_for_dj_11_Mutant_Remove_u_P30_Q...,30,Remove,0.0,Add,NaN,h,37,4.651163,5793.069563,100.0
4,dj_11,best_solutions_for_Mutant_dj_11_QGI_58_P8.csv,8,QGI,0.0,Delete,y,NaN,8,0.000000,6.579843,100.0
6,ghz_13,best_solutions_for_ghz_13_Mutant_Add_rx_P5_Q8_...,5,Add,0.0,Delete,rx,NaN,5,0.000000,6.197106,100.0
11,graphstate_12,best_solutions_for_Mutant_graphstate_12_QGI_73...,5,QGI,0.0,Delete,y,NaN,5,0.000000,6.618479,100.0
12,grover_4,best_solutions_for_grover_4_Mutant_Remove_p_P1...,19,Remove,0.0,Add,cx,z,7,42.857143,50.817927,100.0
13,grover_4,best_solutions_for_Mutant_grover_4_QGI_367_P32...,32,QGI,0.0,Delete,ry,NaN,32,0.000000,6.817854,100.0
14,grover_4,best_solutions_for_Mutant_grover_4_QGR_833_P39...,39,QGR,0.0,Add,cx,rxx,36,83.673469,164.207464,100.0
15,qaoa_6,best_solutions_for_qaoa_6_Mutant_Add_swap_P9_Q...,9,Add,0.0,Delete,swap,NaN,9,0.000000,6.209644,100.0
19,qft_9,best_solutions_for_qft_9_Mutant_Add_swap_P11_Q...,11,Add,0.0,Delete,swap,NaN,11,0.000000,6.542583,100.0
20,qft_9,best_solutions_for_qft_9_Mutant_Remove_cp_P23_...,23,Remove,0.0,Add,cp,crz,11,32.203390,6313.353427,100.0
21,qnn_2,best_solutions_for_Mutant_qnn_2_QGR_208_P7.csv,7,QGR,0.0,Replace,iswap,cx,7,5.555556,18.221934,100.0
22,qnn_2,best_solutions_for_qnn_2_Mutant_Add_rx_P9_Q0_[...,9,Add,0.0,Delete,rx,NaN,9,0.000000,6.467602,100.0
23,qnn_2,best_solutions_for_qnn_2_Mutant_Remove_ry_P11_...,11,Remove,0.0,Add,u,rx,0,72.222222,62.094230,100.0
24,qpe_8,best_solutions_for_Mutant_qpe_8_QGI_296_P24.csv,24,QGI,0.0,Delete,x,NaN,24,0.000000,6.816455,100.0
26,qpe_8,best_solutions_for_qpe_8_Mutant_Remove_h_P6_Q6...,6,Remove,0.0,Add,h,ry,0,94.545455,135.698701,100.0
27,qwalk_5,best_solutions_for_Mutant_qwalk_5_QGI_339_P40.csv,40,QGI,0.0,Delete,sdg,NaN,40,0.000000,7.406415,100.0
28,qwalk_5,best_solutions_for_qwalk_5_Mutant_Remove_x_P13...,13,Remove,0.0,Add,u,x,15,70.909091,212.054323,100.0
29,qwalk_5,best_solutions_for_qwalk_5_Mutant_Replace_t_P5...,5,Replace,0.0,Add,rccx,r,9,20.000000,431.694072,100.0
30,vqe_7,best_solutions_for_Mutant_vqe_7_QGI_347_P25.csv,25,QGI,0.0,Delete,rx,NaN,25,0.000000,6.366112,100.0
31,vqe_7,best_solutions_for_Mutant_vqe_7_QGR_752_P24.csv,24,QGR,0.0,Replace,rx,cx,24,0.000000,2574.960093,100.0
32,vqe_7,best_solutions_for_vqe_7_Mutant_Remove_ry_P2_Q...,2,Remove,0.0,Replace,ry,ry,0,41.463415,2810.067075,100.0
33,wstate_10,best_solutions_for_wstate_10_Mutant_Add_rxx_P2...,20,Add,0.0,Delete,rxx,NaN,20,0.000000,6.611835,100.0
34,wstate_10,best_solutions_for_wstate_10_Mutant_Remove_ry_...,1,Remove,0.0,Add,ry,ry,1,0.000000,848.990076,100.0
37,bugs4q-id26,best_solutions_for_Bug4Q_id26.csv,2,Replace,0.0,Replace,h,rx,1,0.000000,17.291166,100.0
38,bugs4q-id27,best_solutions_for_Bug4Q_id27.csv,8,Reverse,0.0,Add,t,swap,7,76.470588,82.627925,100.0